// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	Verify(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Token, error)
	//rpc GenerateToken(Request) returns (Response) {};
	DestroyToken(ctx context.Context, in *TokenString, opts ...client.CallOption) (*NullResult, error)
	VertifyToken(ctx context.Context, in *TokenString, opts ...client.CallOption) (*VerifyResponse, error)
	OpensfiftVerify(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*OpenshiftAuthResult, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "auth"
	}
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Verify(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.name, "Auth.Verify", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) DestroyToken(ctx context.Context, in *TokenString, opts ...client.CallOption) (*NullResult, error) {
	req := c.c.NewRequest(c.name, "Auth.DestroyToken", in)
	out := new(NullResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) VertifyToken(ctx context.Context, in *TokenString, opts ...client.CallOption) (*VerifyResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.VertifyToken", in)
	out := new(VerifyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) OpensfiftVerify(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*OpenshiftAuthResult, error) {
	req := c.c.NewRequest(c.name, "Auth.OpensfiftVerify", in)
	out := new(OpenshiftAuthResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	Verify(context.Context, *LoginRequest, *Token) error
	//rpc GenerateToken(Request) returns (Response) {};
	DestroyToken(context.Context, *TokenString, *NullResult) error
	VertifyToken(context.Context, *TokenString, *VerifyResponse) error
	OpensfiftVerify(context.Context, *LoginRequest, *OpenshiftAuthResult) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		Verify(ctx context.Context, in *LoginRequest, out *Token) error
		DestroyToken(ctx context.Context, in *TokenString, out *NullResult) error
		VertifyToken(ctx context.Context, in *TokenString, out *VerifyResponse) error
		OpensfiftVerify(ctx context.Context, in *LoginRequest, out *OpenshiftAuthResult) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) Verify(ctx context.Context, in *LoginRequest, out *Token) error {
	return h.AuthHandler.Verify(ctx, in, out)
}

func (h *authHandler) DestroyToken(ctx context.Context, in *TokenString, out *NullResult) error {
	return h.AuthHandler.DestroyToken(ctx, in, out)
}

func (h *authHandler) VertifyToken(ctx context.Context, in *TokenString, out *VerifyResponse) error {
	return h.AuthHandler.VertifyToken(ctx, in, out)
}

func (h *authHandler) OpensfiftVerify(ctx context.Context, in *LoginRequest, out *OpenshiftAuthResult) error {
	return h.AuthHandler.OpensfiftVerify(ctx, in, out)
}
