// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=TokenType,proto3" json:"TokenType,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,3,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type TokenString struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenString) Reset()         { *m = TokenString{} }
func (m *TokenString) String() string { return proto.CompactTextString(m) }
func (*TokenString) ProtoMessage()    {}
func (*TokenString) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *TokenString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenString.Unmarshal(m, b)
}
func (m *TokenString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenString.Marshal(b, m, deterministic)
}
func (m *TokenString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenString.Merge(m, src)
}
func (m *TokenString) XXX_Size() int {
	return xxx_messageInfo_TokenString.Size(m)
}
func (m *TokenString) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenString.DiscardUnknown(m)
}

var xxx_messageInfo_TokenString proto.InternalMessageInfo

func (m *TokenString) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Request struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*TokenString)(nil), "auth.TokenString")
	proto.RegisterType((*VerifyResponse)(nil), "auth.VerifyResponse")
	proto.RegisterType((*Request)(nil), "auth.Request")
	proto.RegisterType((*Response)(nil), "auth.Response")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x05, 0xa9, 0xb5, 0x1d, 0xb0, 0xd1, 0x4d, 0x0f, 0x84, 0xf4, 0x40, 0xd6, 0x4b, 0x13, 0x93,
	0x9a, 0xe8, 0xc9, 0x23, 0x89, 0x7a, 0xf2, 0x84, 0xb5, 0x77, 0x6c, 0xa7, 0x74, 0x63, 0x60, 0x71,
	0x67, 0x89, 0xf2, 0x35, 0xfe, 0xaa, 0x81, 0x5d, 0x2c, 0x9e, 0xbd, 0xcd, 0x7b, 0x6f, 0x78, 0x6f,
	0x78, 0x59, 0x80, 0xac, 0xd6, 0x87, 0x55, 0xa5, 0xa4, 0x96, 0x6c, 0xd4, 0xce, 0xfc, 0x09, 0x82,
	0x67, 0x99, 0x8b, 0x32, 0xc5, 0x8f, 0x1a, 0x49, 0xb3, 0x08, 0x26, 0x35, 0xa1, 0x2a, 0xb3, 0x02,
	0x43, 0x37, 0x76, 0x97, 0xd3, 0xf4, 0x17, 0xb7, 0x5a, 0x95, 0x11, 0x7d, 0x4a, 0xb5, 0x0b, 0x4f,
	0x8c, 0xd6, 0x63, 0x8e, 0x70, 0xba, 0x96, 0xef, 0x58, 0xb2, 0x18, 0xfc, 0x64, 0xbb, 0x45, 0xa2,
	0x0e, 0x5a, 0x8f, 0x21, 0xc5, 0x16, 0x30, 0xed, 0x86, 0x75, 0x53, 0xa1, 0xf5, 0x39, 0x12, 0xad,
	0xfa, 0xf8, 0x55, 0x09, 0x85, 0x94, 0xe8, 0xd0, 0x8b, 0xdd, 0xa5, 0x97, 0x1e, 0x09, 0x7e, 0x05,
	0x7e, 0xb7, 0xfa, 0xa2, 0x95, 0x28, 0x73, 0x36, 0xb7, 0xa9, 0x36, 0xc6, 0x00, 0xce, 0x61, 0xb6,
	0x41, 0x25, 0xf6, 0x4d, 0x8a, 0x54, 0xc9, 0x92, 0x90, 0x5d, 0x80, 0xf7, 0x2a, 0x76, 0x76, 0xab,
	0x1d, 0x79, 0x02, 0x67, 0xff, 0xfd, 0xe5, 0x05, 0x4c, 0x86, 0x01, 0x05, 0xe5, 0x7d, 0x40, 0x41,
	0xf9, 0xed, 0xb7, 0x0b, 0xa3, 0xa4, 0xd6, 0x07, 0x76, 0x0d, 0x63, 0x73, 0x0d, 0x63, 0xab, 0xae,
	0xfe, 0x61, 0xdf, 0x91, 0x6f, 0x38, 0x73, 0xb8, 0xc3, 0x6e, 0x20, 0x78, 0x40, 0xd2, 0x4a, 0x36,
	0xa6, 0xab, 0x73, 0x23, 0xf7, 0xdb, 0xb3, 0x1e, 0x9a, 0x58, 0xee, 0xb0, 0x7b, 0x08, 0x36, 0xa8,
	0xb4, 0xd8, 0xdb, 0x0f, 0x2e, 0x07, 0x7e, 0xa6, 0xa4, 0x68, 0x6e, 0xa8, 0xbf, 0x95, 0x70, 0xe7,
	0x6d, 0xdc, 0xbd, 0x83, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x26, 0xed, 0xb1, 0x15,
	0x02, 0x00, 0x00,
}
