version: '3'
services:
  consul:
    image: progrium/consul:latest
    command:
      - -server
      - -bootstrap
      - rejoin
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  api:
    build:
      context: .
      dockerfile: "build/api/Dockerfile"
    command:
      - --registry_address=consul:8500
    depends_on:
      - consul
      - auth
    ports:
      - "8080:8080"
  auth:
    build:
      context: .
      dockerfile: "build/auth/Dockerfile"
    command:
      - --registry_address=consul:8500
    depends_on:
      - consul
