// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"caas-micro/internal/app/api"
	"caas-micro/internal/app/api/controller"
	"caas-micro/internal/app/api/rpcclients"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApiApplication() *api.ApiApplication {
	authService := rpcclients.NewAuthSrvClient()
	loginController := controller.NewLoginController(authService)
	userService := rpcclients.NewUserSrvClient()
	userController := controller.NewUserController(userService)
	apiApplication := api.NewApiApplication(loginController, userController)
	return apiApplication
}

// wire.go:

var providerSet = wire.NewSet(api.ProviderSet, controller.ProviderSet, rpcclients.ProviderSet)
