// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"caas-micro/internal/app/auth"
	"caas-micro/internal/app/auth/rpcclients"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateAuthServer() (*auth.AuthServer, error) {
	auther, err := auth.NewAuther()
	if err != nil {
		return nil, err
	}
	userService, err := rpcclients.NewUserSrvClient()
	if err != nil {
		return nil, err
	}
	authServer, err := auth.NewAuthServer(auther, userService)
	if err != nil {
		return nil, err
	}
	return authServer, nil
}

// wire.go:

var providerSet = wire.NewSet(auth.ProviderSet, rpcclients.ProviderSet)
