// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"caas-micro/internal/app/user"
	"caas-micro/internal/app/user/rpcclients"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateUserServer() (*user.UserServer, error) {
	authService, err := rpcclients.NewAuthSrvClient()
	if err != nil {
		return nil, err
	}
	userServer, err := user.NewUserServer(authService)
	if err != nil {
		return nil, err
	}
	return userServer, nil
}

// wire.go:

var providerSet = wire.NewSet(user.ProviderSet, rpcclients.ProviderSet)
