// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRequest struct {
	UserName             string            `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	LikeUserName         string            `protobuf:"bytes,2,opt,name=LikeUserName,proto3" json:"LikeUserName,omitempty"`
	LikeRealName         string            `protobuf:"bytes,3,opt,name=LikeRealName,proto3" json:"LikeRealName,omitempty"`
	Email                string            `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Status               int64             `protobuf:"zigzag64,5,opt,name=Status,proto3" json:"Status,omitempty"`
	RoleIDS              []string          `protobuf:"bytes,6,rep,name=RoleIDS,proto3" json:"RoleIDS,omitempty"`
	QueryOpt             *UserQueryOptions `protobuf:"bytes,7,opt,name=QueryOpt,proto3" json:"QueryOpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *QueryRequest) GetLikeUserName() string {
	if m != nil {
		return m.LikeUserName
	}
	return ""
}

func (m *QueryRequest) GetLikeRealName() string {
	if m != nil {
		return m.LikeRealName
	}
	return ""
}

func (m *QueryRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *QueryRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *QueryRequest) GetRoleIDS() []string {
	if m != nil {
		return m.RoleIDS
	}
	return nil
}

func (m *QueryRequest) GetQueryOpt() *UserQueryOptions {
	if m != nil {
		return m.QueryOpt
	}
	return nil
}

type QueryResult struct {
	Data                 []*UserSchema     `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	PageResult           *PaginationResult `protobuf:"bytes,2,opt,name=PageResult,proto3" json:"PageResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetData() []*UserSchema {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryResult) GetPageResult() *PaginationResult {
	if m != nil {
		return m.PageResult
	}
	return nil
}

type UserQueryOptions struct {
	IncludeRoles         bool             `protobuf:"varint,1,opt,name=IncludeRoles,proto3" json:"IncludeRoles,omitempty"`
	PageParam            *PaginationParam `protobuf:"bytes,2,opt,name=PageParam,proto3" json:"PageParam,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserQueryOptions) Reset()         { *m = UserQueryOptions{} }
func (m *UserQueryOptions) String() string { return proto.CompactTextString(m) }
func (*UserQueryOptions) ProtoMessage()    {}
func (*UserQueryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserQueryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryOptions.Unmarshal(m, b)
}
func (m *UserQueryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryOptions.Marshal(b, m, deterministic)
}
func (m *UserQueryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryOptions.Merge(m, src)
}
func (m *UserQueryOptions) XXX_Size() int {
	return xxx_messageInfo_UserQueryOptions.Size(m)
}
func (m *UserQueryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryOptions proto.InternalMessageInfo

func (m *UserQueryOptions) GetIncludeRoles() bool {
	if m != nil {
		return m.IncludeRoles
	}
	return false
}

func (m *UserQueryOptions) GetPageParam() *PaginationParam {
	if m != nil {
		return m.PageParam
	}
	return nil
}

type GetUserRequest struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	QueryOpt             *UserQueryOptions `protobuf:"bytes,2,opt,name=QueryOpt,proto3" json:"QueryOpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetUserRequest) GetQueryOpt() *UserQueryOptions {
	if m != nil {
		return m.QueryOpt
	}
	return nil
}

type DeleteUserRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UpdateUserRequest struct {
	Uid                  string      `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	User                 *UserSchema `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserRequest) GetUser() *UserSchema {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserStatusRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Status               int64    `protobuf:"zigzag64,2,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserStatusRequest) Reset()         { *m = UpdateUserStatusRequest{} }
func (m *UpdateUserStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserStatusRequest) ProtoMessage()    {}
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UpdateUserStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserStatusRequest.Unmarshal(m, b)
}
func (m *UpdateUserStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserStatusRequest.Merge(m, src)
}
func (m *UpdateUserStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserStatusRequest.Size(m)
}
func (m *UpdateUserStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserStatusRequest proto.InternalMessageInfo

func (m *UpdateUserStatusRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateUserStatusRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CurrentUserResult struct {
	RecordID             string   `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	RealName             string   `protobuf:"bytes,3,opt,name=RealName,proto3" json:"RealName,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	RoleNames            []string `protobuf:"bytes,7,rep,name=RoleNames,proto3" json:"RoleNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentUserResult) Reset()         { *m = CurrentUserResult{} }
func (m *CurrentUserResult) String() string { return proto.CompactTextString(m) }
func (*CurrentUserResult) ProtoMessage()    {}
func (*CurrentUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *CurrentUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentUserResult.Unmarshal(m, b)
}
func (m *CurrentUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentUserResult.Marshal(b, m, deterministic)
}
func (m *CurrentUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentUserResult.Merge(m, src)
}
func (m *CurrentUserResult) XXX_Size() int {
	return xxx_messageInfo_CurrentUserResult.Size(m)
}
func (m *CurrentUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentUserResult proto.InternalMessageInfo

func (m *CurrentUserResult) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *CurrentUserResult) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CurrentUserResult) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *CurrentUserResult) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CurrentUserResult) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CurrentUserResult) GetRoleNames() []string {
	if m != nil {
		return m.RoleNames
	}
	return nil
}

type UpdatePassRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=OldPassword,proto3" json:"OldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePassRequest) Reset()         { *m = UpdatePassRequest{} }
func (m *UpdatePassRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePassRequest) ProtoMessage()    {}
func (*UpdatePassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UpdatePassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePassRequest.Unmarshal(m, b)
}
func (m *UpdatePassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePassRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePassRequest.Merge(m, src)
}
func (m *UpdatePassRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePassRequest.Size(m)
}
func (m *UpdatePassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePassRequest proto.InternalMessageInfo

func (m *UpdatePassRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdatePassRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UpdatePassRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type NullResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullResult) Reset()         { *m = NullResult{} }
func (m *NullResult) String() string { return proto.CompactTextString(m) }
func (*NullResult) ProtoMessage()    {}
func (*NullResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *NullResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullResult.Unmarshal(m, b)
}
func (m *NullResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullResult.Marshal(b, m, deterministic)
}
func (m *NullResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullResult.Merge(m, src)
}
func (m *NullResult) XXX_Size() int {
	return xxx_messageInfo_NullResult.Size(m)
}
func (m *NullResult) XXX_DiscardUnknown() {
	xxx_messageInfo_NullResult.DiscardUnknown(m)
}

var xxx_messageInfo_NullResult proto.InternalMessageInfo

type UserSchema struct {
	RecordID             string               `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	RealName             string               `protobuf:"bytes,3,opt,name=RealName,proto3" json:"RealName,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Phone                string               `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	Status               int64                `protobuf:"zigzag64,7,opt,name=Status,proto3" json:"Status,omitempty"`
	Creator              string               `protobuf:"bytes,8,opt,name=Creator,proto3" json:"Creator,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Roles                []*UserRole          `protobuf:"bytes,10,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserSchema) Reset()         { *m = UserSchema{} }
func (m *UserSchema) String() string { return proto.CompactTextString(m) }
func (*UserSchema) ProtoMessage()    {}
func (*UserSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *UserSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSchema.Unmarshal(m, b)
}
func (m *UserSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSchema.Marshal(b, m, deterministic)
}
func (m *UserSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSchema.Merge(m, src)
}
func (m *UserSchema) XXX_Size() int {
	return xxx_messageInfo_UserSchema.Size(m)
}
func (m *UserSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSchema.DiscardUnknown(m)
}

var xxx_messageInfo_UserSchema proto.InternalMessageInfo

func (m *UserSchema) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *UserSchema) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserSchema) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *UserSchema) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserSchema) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserSchema) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserSchema) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserSchema) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *UserSchema) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserSchema) GetRoles() []*UserRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UserRole struct {
	RoleID               string   `protobuf:"bytes,1,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetRoleID() string {
	if m != nil {
		return m.RoleID
	}
	return ""
}

type PaginationResult struct {
	Total                int64    `protobuf:"zigzag64,1,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationResult) Reset()         { *m = PaginationResult{} }
func (m *PaginationResult) String() string { return proto.CompactTextString(m) }
func (*PaginationResult) ProtoMessage()    {}
func (*PaginationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *PaginationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationResult.Unmarshal(m, b)
}
func (m *PaginationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationResult.Marshal(b, m, deterministic)
}
func (m *PaginationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationResult.Merge(m, src)
}
func (m *PaginationResult) XXX_Size() int {
	return xxx_messageInfo_PaginationResult.Size(m)
}
func (m *PaginationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationResult.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationResult proto.InternalMessageInfo

func (m *PaginationResult) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PaginationParam struct {
	PageIndex            int64    `protobuf:"zigzag64,1,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	PageSize             int64    `protobuf:"zigzag64,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationParam) Reset()         { *m = PaginationParam{} }
func (m *PaginationParam) String() string { return proto.CompactTextString(m) }
func (*PaginationParam) ProtoMessage()    {}
func (*PaginationParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *PaginationParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationParam.Unmarshal(m, b)
}
func (m *PaginationParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationParam.Marshal(b, m, deterministic)
}
func (m *PaginationParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationParam.Merge(m, src)
}
func (m *PaginationParam) XXX_Size() int {
	return xxx_messageInfo_PaginationParam.Size(m)
}
func (m *PaginationParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationParam.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationParam proto.InternalMessageInfo

func (m *PaginationParam) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *PaginationParam) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type UserShow struct {
	RecordID             string               `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	RealName             string               `protobuf:"bytes,3,opt,name=RealName,proto3" json:"RealName,omitempty"`
	Phone                string               `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Status               int64                `protobuf:"zigzag64,6,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Roles                []*RoleSchema        `protobuf:"bytes,8,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserShow) Reset()         { *m = UserShow{} }
func (m *UserShow) String() string { return proto.CompactTextString(m) }
func (*UserShow) ProtoMessage()    {}
func (*UserShow) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *UserShow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserShow.Unmarshal(m, b)
}
func (m *UserShow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserShow.Marshal(b, m, deterministic)
}
func (m *UserShow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserShow.Merge(m, src)
}
func (m *UserShow) XXX_Size() int {
	return xxx_messageInfo_UserShow.Size(m)
}
func (m *UserShow) XXX_DiscardUnknown() {
	xxx_messageInfo_UserShow.DiscardUnknown(m)
}

var xxx_messageInfo_UserShow proto.InternalMessageInfo

func (m *UserShow) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *UserShow) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserShow) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *UserShow) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserShow) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserShow) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserShow) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserShow) GetRoles() []*RoleSchema {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UserShowQueryResult struct {
	Data                 []*UserShow       `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	PageResult           *PaginationResult `protobuf:"bytes,2,opt,name=PageResult,proto3" json:"PageResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserShowQueryResult) Reset()         { *m = UserShowQueryResult{} }
func (m *UserShowQueryResult) String() string { return proto.CompactTextString(m) }
func (*UserShowQueryResult) ProtoMessage()    {}
func (*UserShowQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *UserShowQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserShowQueryResult.Unmarshal(m, b)
}
func (m *UserShowQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserShowQueryResult.Marshal(b, m, deterministic)
}
func (m *UserShowQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserShowQueryResult.Merge(m, src)
}
func (m *UserShowQueryResult) XXX_Size() int {
	return xxx_messageInfo_UserShowQueryResult.Size(m)
}
func (m *UserShowQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserShowQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserShowQueryResult proto.InternalMessageInfo

func (m *UserShowQueryResult) GetData() []*UserShow {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserShowQueryResult) GetPageResult() *PaginationResult {
	if m != nil {
		return m.PageResult
	}
	return nil
}

type RoleSchema struct {
	RecordID             string               `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Sequence             int64                `protobuf:"zigzag64,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Memo                 string               `protobuf:"bytes,4,opt,name=Memo,proto3" json:"Memo,omitempty"`
	Creator              string               `protobuf:"bytes,5,opt,name=Creator,proto3" json:"Creator,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Menus                []*RoleMenu          `protobuf:"bytes,7,rep,name=Menus,proto3" json:"Menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RoleSchema) Reset()         { *m = RoleSchema{} }
func (m *RoleSchema) String() string { return proto.CompactTextString(m) }
func (*RoleSchema) ProtoMessage()    {}
func (*RoleSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *RoleSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleSchema.Unmarshal(m, b)
}
func (m *RoleSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleSchema.Marshal(b, m, deterministic)
}
func (m *RoleSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleSchema.Merge(m, src)
}
func (m *RoleSchema) XXX_Size() int {
	return xxx_messageInfo_RoleSchema.Size(m)
}
func (m *RoleSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleSchema.DiscardUnknown(m)
}

var xxx_messageInfo_RoleSchema proto.InternalMessageInfo

func (m *RoleSchema) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *RoleSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleSchema) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *RoleSchema) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *RoleSchema) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RoleSchema) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RoleSchema) GetMenus() []*RoleMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

type RoleMenu struct {
	MenuID               string   `protobuf:"bytes,1,opt,name=MenuID,proto3" json:"MenuID,omitempty"`
	Actions              []string `protobuf:"bytes,2,rep,name=Actions,proto3" json:"Actions,omitempty"`
	Resources            []string `protobuf:"bytes,3,rep,name=Resources,proto3" json:"Resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMenu) Reset()         { *m = RoleMenu{} }
func (m *RoleMenu) String() string { return proto.CompactTextString(m) }
func (*RoleMenu) ProtoMessage()    {}
func (*RoleMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{17}
}

func (m *RoleMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMenu.Unmarshal(m, b)
}
func (m *RoleMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMenu.Marshal(b, m, deterministic)
}
func (m *RoleMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMenu.Merge(m, src)
}
func (m *RoleMenu) XXX_Size() int {
	return xxx_messageInfo_RoleMenu.Size(m)
}
func (m *RoleMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMenu.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMenu proto.InternalMessageInfo

func (m *RoleMenu) GetMenuID() string {
	if m != nil {
		return m.MenuID
	}
	return ""
}

func (m *RoleMenu) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *RoleMenu) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type RoleQueryParam struct {
	RecordIDs            []string          `protobuf:"bytes,1,rep,name=RecordIDs,proto3" json:"RecordIDs,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	LikeName             string            `protobuf:"bytes,3,opt,name=LikeName,proto3" json:"LikeName,omitempty"`
	UserID               string            `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	QueryOpt             *RoleQueryOptions `protobuf:"bytes,5,opt,name=QueryOpt,proto3" json:"QueryOpt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoleQueryParam) Reset()         { *m = RoleQueryParam{} }
func (m *RoleQueryParam) String() string { return proto.CompactTextString(m) }
func (*RoleQueryParam) ProtoMessage()    {}
func (*RoleQueryParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{18}
}

func (m *RoleQueryParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleQueryParam.Unmarshal(m, b)
}
func (m *RoleQueryParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleQueryParam.Marshal(b, m, deterministic)
}
func (m *RoleQueryParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleQueryParam.Merge(m, src)
}
func (m *RoleQueryParam) XXX_Size() int {
	return xxx_messageInfo_RoleQueryParam.Size(m)
}
func (m *RoleQueryParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleQueryParam.DiscardUnknown(m)
}

var xxx_messageInfo_RoleQueryParam proto.InternalMessageInfo

func (m *RoleQueryParam) GetRecordIDs() []string {
	if m != nil {
		return m.RecordIDs
	}
	return nil
}

func (m *RoleQueryParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleQueryParam) GetLikeName() string {
	if m != nil {
		return m.LikeName
	}
	return ""
}

func (m *RoleQueryParam) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RoleQueryParam) GetQueryOpt() *RoleQueryOptions {
	if m != nil {
		return m.QueryOpt
	}
	return nil
}

type RoleQueryOptions struct {
	IncludeMenus         bool             `protobuf:"varint,1,opt,name=IncludeMenus,proto3" json:"IncludeMenus,omitempty"`
	PageParam            *PaginationParam `protobuf:"bytes,2,opt,name=PageParam,proto3" json:"PageParam,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoleQueryOptions) Reset()         { *m = RoleQueryOptions{} }
func (m *RoleQueryOptions) String() string { return proto.CompactTextString(m) }
func (*RoleQueryOptions) ProtoMessage()    {}
func (*RoleQueryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{19}
}

func (m *RoleQueryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleQueryOptions.Unmarshal(m, b)
}
func (m *RoleQueryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleQueryOptions.Marshal(b, m, deterministic)
}
func (m *RoleQueryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleQueryOptions.Merge(m, src)
}
func (m *RoleQueryOptions) XXX_Size() int {
	return xxx_messageInfo_RoleQueryOptions.Size(m)
}
func (m *RoleQueryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleQueryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RoleQueryOptions proto.InternalMessageInfo

func (m *RoleQueryOptions) GetIncludeMenus() bool {
	if m != nil {
		return m.IncludeMenus
	}
	return false
}

func (m *RoleQueryOptions) GetPageParam() *PaginationParam {
	if m != nil {
		return m.PageParam
	}
	return nil
}

type RoleQueryResult struct {
	Data                 []*RoleSchema     `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	PageResult           *PaginationResult `protobuf:"bytes,2,opt,name=PageResult,proto3" json:"PageResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RoleQueryResult) Reset()         { *m = RoleQueryResult{} }
func (m *RoleQueryResult) String() string { return proto.CompactTextString(m) }
func (*RoleQueryResult) ProtoMessage()    {}
func (*RoleQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{20}
}

func (m *RoleQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleQueryResult.Unmarshal(m, b)
}
func (m *RoleQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleQueryResult.Marshal(b, m, deterministic)
}
func (m *RoleQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleQueryResult.Merge(m, src)
}
func (m *RoleQueryResult) XXX_Size() int {
	return xxx_messageInfo_RoleQueryResult.Size(m)
}
func (m *RoleQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_RoleQueryResult proto.InternalMessageInfo

func (m *RoleQueryResult) GetData() []*RoleSchema {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoleQueryResult) GetPageResult() *PaginationResult {
	if m != nil {
		return m.PageResult
	}
	return nil
}

type MenuSchema struct {
	RecordID             string               `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Sequence             int64                `protobuf:"zigzag64,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Icon                 string               `protobuf:"bytes,4,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Router               string               `protobuf:"bytes,5,opt,name=Router,proto3" json:"Router,omitempty"`
	Hidden               int64                `protobuf:"zigzag64,6,opt,name=Hidden,proto3" json:"Hidden,omitempty"`
	ParentID             string               `protobuf:"bytes,7,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ParentPath           string               `protobuf:"bytes,8,opt,name=ParentPath,proto3" json:"ParentPath,omitempty"`
	Creator              string               `protobuf:"bytes,9,opt,name=Creator,proto3" json:"Creator,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Actions              []*MenuAction        `protobuf:"bytes,11,rep,name=Actions,proto3" json:"Actions,omitempty"`
	Resources            []*MenuResource      `protobuf:"bytes,12,rep,name=Resources,proto3" json:"Resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MenuSchema) Reset()         { *m = MenuSchema{} }
func (m *MenuSchema) String() string { return proto.CompactTextString(m) }
func (*MenuSchema) ProtoMessage()    {}
func (*MenuSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{21}
}

func (m *MenuSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuSchema.Unmarshal(m, b)
}
func (m *MenuSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuSchema.Marshal(b, m, deterministic)
}
func (m *MenuSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuSchema.Merge(m, src)
}
func (m *MenuSchema) XXX_Size() int {
	return xxx_messageInfo_MenuSchema.Size(m)
}
func (m *MenuSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuSchema.DiscardUnknown(m)
}

var xxx_messageInfo_MenuSchema proto.InternalMessageInfo

func (m *MenuSchema) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *MenuSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuSchema) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MenuSchema) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MenuSchema) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *MenuSchema) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *MenuSchema) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *MenuSchema) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

func (m *MenuSchema) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MenuSchema) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *MenuSchema) GetActions() []*MenuAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *MenuSchema) GetResources() []*MenuResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type MenuAction struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuAction) Reset()         { *m = MenuAction{} }
func (m *MenuAction) String() string { return proto.CompactTextString(m) }
func (*MenuAction) ProtoMessage()    {}
func (*MenuAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{22}
}

func (m *MenuAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuAction.Unmarshal(m, b)
}
func (m *MenuAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuAction.Marshal(b, m, deterministic)
}
func (m *MenuAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuAction.Merge(m, src)
}
func (m *MenuAction) XXX_Size() int {
	return xxx_messageInfo_MenuAction.Size(m)
}
func (m *MenuAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuAction.DiscardUnknown(m)
}

var xxx_messageInfo_MenuAction proto.InternalMessageInfo

func (m *MenuAction) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MenuAction) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MenuResource struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuResource) Reset()         { *m = MenuResource{} }
func (m *MenuResource) String() string { return proto.CompactTextString(m) }
func (*MenuResource) ProtoMessage()    {}
func (*MenuResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{23}
}

func (m *MenuResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuResource.Unmarshal(m, b)
}
func (m *MenuResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuResource.Marshal(b, m, deterministic)
}
func (m *MenuResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuResource.Merge(m, src)
}
func (m *MenuResource) XXX_Size() int {
	return xxx_messageInfo_MenuResource.Size(m)
}
func (m *MenuResource) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuResource.DiscardUnknown(m)
}

var xxx_messageInfo_MenuResource proto.InternalMessageInfo

func (m *MenuResource) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *MenuResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuResource) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *MenuResource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type MenuQueryParam struct {
	RecordIDs            []string `protobuf:"bytes,1,rep,name=RecordIDs,proto3" json:"RecordIDs,omitempty"`
	LikeName             string   `protobuf:"bytes,2,opt,name=LikeName,proto3" json:"LikeName,omitempty"`
	ParentID             string   `protobuf:"bytes,3,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	PrefixParentPath     string   `protobuf:"bytes,4,opt,name=PrefixParentPath,proto3" json:"PrefixParentPath,omitempty"`
	Hidden               int64    `protobuf:"zigzag64,5,opt,name=Hidden,proto3" json:"Hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuQueryParam) Reset()         { *m = MenuQueryParam{} }
func (m *MenuQueryParam) String() string { return proto.CompactTextString(m) }
func (*MenuQueryParam) ProtoMessage()    {}
func (*MenuQueryParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{24}
}

func (m *MenuQueryParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuQueryParam.Unmarshal(m, b)
}
func (m *MenuQueryParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuQueryParam.Marshal(b, m, deterministic)
}
func (m *MenuQueryParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuQueryParam.Merge(m, src)
}
func (m *MenuQueryParam) XXX_Size() int {
	return xxx_messageInfo_MenuQueryParam.Size(m)
}
func (m *MenuQueryParam) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuQueryParam.DiscardUnknown(m)
}

var xxx_messageInfo_MenuQueryParam proto.InternalMessageInfo

func (m *MenuQueryParam) GetRecordIDs() []string {
	if m != nil {
		return m.RecordIDs
	}
	return nil
}

func (m *MenuQueryParam) GetLikeName() string {
	if m != nil {
		return m.LikeName
	}
	return ""
}

func (m *MenuQueryParam) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *MenuQueryParam) GetPrefixParentPath() string {
	if m != nil {
		return m.PrefixParentPath
	}
	return ""
}

func (m *MenuQueryParam) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

type MenuQueryOptions struct {
	IncludeActions       bool             `protobuf:"varint,1,opt,name=IncludeActions,proto3" json:"IncludeActions,omitempty"`
	IncludeResources     bool             `protobuf:"varint,2,opt,name=IncludeResources,proto3" json:"IncludeResources,omitempty"`
	PageParam            *PaginationParam `protobuf:"bytes,3,opt,name=PageParam,proto3" json:"PageParam,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MenuQueryOptions) Reset()         { *m = MenuQueryOptions{} }
func (m *MenuQueryOptions) String() string { return proto.CompactTextString(m) }
func (*MenuQueryOptions) ProtoMessage()    {}
func (*MenuQueryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{25}
}

func (m *MenuQueryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuQueryOptions.Unmarshal(m, b)
}
func (m *MenuQueryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuQueryOptions.Marshal(b, m, deterministic)
}
func (m *MenuQueryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuQueryOptions.Merge(m, src)
}
func (m *MenuQueryOptions) XXX_Size() int {
	return xxx_messageInfo_MenuQueryOptions.Size(m)
}
func (m *MenuQueryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuQueryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MenuQueryOptions proto.InternalMessageInfo

func (m *MenuQueryOptions) GetIncludeActions() bool {
	if m != nil {
		return m.IncludeActions
	}
	return false
}

func (m *MenuQueryOptions) GetIncludeResources() bool {
	if m != nil {
		return m.IncludeResources
	}
	return false
}

func (m *MenuQueryOptions) GetPageParam() *PaginationParam {
	if m != nil {
		return m.PageParam
	}
	return nil
}

type MenuQueryResult struct {
	Data                 []*MenuSchema     `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	PageResult           *PaginationResult `protobuf:"bytes,2,opt,name=PageResult,proto3" json:"PageResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MenuQueryResult) Reset()         { *m = MenuQueryResult{} }
func (m *MenuQueryResult) String() string { return proto.CompactTextString(m) }
func (*MenuQueryResult) ProtoMessage()    {}
func (*MenuQueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{26}
}

func (m *MenuQueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuQueryResult.Unmarshal(m, b)
}
func (m *MenuQueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuQueryResult.Marshal(b, m, deterministic)
}
func (m *MenuQueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuQueryResult.Merge(m, src)
}
func (m *MenuQueryResult) XXX_Size() int {
	return xxx_messageInfo_MenuQueryResult.Size(m)
}
func (m *MenuQueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuQueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_MenuQueryResult proto.InternalMessageInfo

func (m *MenuQueryResult) GetData() []*MenuSchema {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MenuQueryResult) GetPageResult() *PaginationResult {
	if m != nil {
		return m.PageResult
	}
	return nil
}

type MenuTree struct {
	RecordID             string          `protobuf:"bytes,1,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Sequence             int64           `protobuf:"zigzag64,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Icon                 string          `protobuf:"bytes,4,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Router               string          `protobuf:"bytes,5,opt,name=Router,proto3" json:"Router,omitempty"`
	Hidden               int64           `protobuf:"zigzag64,6,opt,name=Hidden,proto3" json:"Hidden,omitempty"`
	ParentID             string          `protobuf:"bytes,7,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ParentPath           string          `protobuf:"bytes,8,opt,name=ParentPath,proto3" json:"ParentPath,omitempty"`
	Actions              []*MenuAction   `protobuf:"bytes,9,rep,name=Actions,proto3" json:"Actions,omitempty"`
	Resources            []*MenuResource `protobuf:"bytes,10,rep,name=Resources,proto3" json:"Resources,omitempty"`
	Children             []*MenuTree     `protobuf:"bytes,11,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MenuTree) Reset()         { *m = MenuTree{} }
func (m *MenuTree) String() string { return proto.CompactTextString(m) }
func (*MenuTree) ProtoMessage()    {}
func (*MenuTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{27}
}

func (m *MenuTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuTree.Unmarshal(m, b)
}
func (m *MenuTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuTree.Marshal(b, m, deterministic)
}
func (m *MenuTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuTree.Merge(m, src)
}
func (m *MenuTree) XXX_Size() int {
	return xxx_messageInfo_MenuTree.Size(m)
}
func (m *MenuTree) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuTree.DiscardUnknown(m)
}

var xxx_messageInfo_MenuTree proto.InternalMessageInfo

func (m *MenuTree) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *MenuTree) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuTree) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MenuTree) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MenuTree) GetRouter() string {
	if m != nil {
		return m.Router
	}
	return ""
}

func (m *MenuTree) GetHidden() int64 {
	if m != nil {
		return m.Hidden
	}
	return 0
}

func (m *MenuTree) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *MenuTree) GetParentPath() string {
	if m != nil {
		return m.ParentPath
	}
	return ""
}

func (m *MenuTree) GetActions() []*MenuAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *MenuTree) GetResources() []*MenuResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *MenuTree) GetChildren() []*MenuTree {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "user.QueryRequest")
	proto.RegisterType((*QueryResult)(nil), "user.QueryResult")
	proto.RegisterType((*UserQueryOptions)(nil), "user.UserQueryOptions")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserStatusRequest)(nil), "user.UpdateUserStatusRequest")
	proto.RegisterType((*CurrentUserResult)(nil), "user.CurrentUserResult")
	proto.RegisterType((*UpdatePassRequest)(nil), "user.UpdatePassRequest")
	proto.RegisterType((*NullResult)(nil), "user.NullResult")
	proto.RegisterType((*UserSchema)(nil), "user.UserSchema")
	proto.RegisterType((*UserRole)(nil), "user.UserRole")
	proto.RegisterType((*PaginationResult)(nil), "user.PaginationResult")
	proto.RegisterType((*PaginationParam)(nil), "user.PaginationParam")
	proto.RegisterType((*UserShow)(nil), "user.UserShow")
	proto.RegisterType((*UserShowQueryResult)(nil), "user.UserShowQueryResult")
	proto.RegisterType((*RoleSchema)(nil), "user.RoleSchema")
	proto.RegisterType((*RoleMenu)(nil), "user.RoleMenu")
	proto.RegisterType((*RoleQueryParam)(nil), "user.RoleQueryParam")
	proto.RegisterType((*RoleQueryOptions)(nil), "user.RoleQueryOptions")
	proto.RegisterType((*RoleQueryResult)(nil), "user.RoleQueryResult")
	proto.RegisterType((*MenuSchema)(nil), "user.MenuSchema")
	proto.RegisterType((*MenuAction)(nil), "user.MenuAction")
	proto.RegisterType((*MenuResource)(nil), "user.MenuResource")
	proto.RegisterType((*MenuQueryParam)(nil), "user.MenuQueryParam")
	proto.RegisterType((*MenuQueryOptions)(nil), "user.MenuQueryOptions")
	proto.RegisterType((*MenuQueryResult)(nil), "user.MenuQueryResult")
	proto.RegisterType((*MenuTree)(nil), "user.MenuTree")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 1259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xb6, 0x7e, 0x2d, 0xb5, 0x55, 0x8a, 0x3c, 0x84, 0x64, 0x51, 0xf1, 0xa3, 0x9a, 0x0a, 0x29,
	0x55, 0x0e, 0x72, 0xca, 0x01, 0x8a, 0x03, 0x1c, 0x5c, 0x16, 0x15, 0x54, 0x21, 0x8e, 0x58, 0xd9,
	0x1c, 0xb8, 0xad, 0xb5, 0x13, 0x6b, 0xcb, 0xab, 0x5d, 0x67, 0x7f, 0xca, 0x81, 0x33, 0xa7, 0xbc,
	0x02, 0x6f, 0xc0, 0x8d, 0x2b, 0x4f, 0xc3, 0x89, 0x23, 0xcf, 0x40, 0x75, 0xcf, 0xcc, 0xee, 0xec,
	0x4a, 0x16, 0x36, 0x2e, 0x5f, 0x38, 0xed, 0x74, 0x4f, 0xcf, 0x4c, 0x6f, 0x7f, 0xfd, 0xf5, 0x4c,
	0x03, 0xa4, 0xb1, 0x88, 0x46, 0x17, 0x51, 0x98, 0x84, 0xac, 0x8e, 0xe3, 0xfe, 0x27, 0x67, 0x61,
	0x78, 0xe6, 0x8b, 0x3d, 0xd2, 0x9d, 0xa6, 0xaf, 0xf7, 0x12, 0x6f, 0x29, 0xe2, 0xc4, 0x59, 0x5e,
	0x48, 0x33, 0xfe, 0x77, 0x05, 0x3a, 0xdf, 0xa7, 0x22, 0xfa, 0xc9, 0x16, 0x6f, 0x52, 0x11, 0x27,
	0xac, 0x0f, 0xad, 0x93, 0x58, 0x44, 0x47, 0xce, 0x52, 0x58, 0x95, 0x41, 0x65, 0xd8, 0xb6, 0x33,
	0x99, 0x71, 0xe8, 0x7c, 0xe7, 0x9d, 0x8b, 0x6c, 0xbe, 0x4a, 0xf3, 0x05, 0x9d, 0xb6, 0xb1, 0x85,
	0xe3, 0x93, 0x4d, 0x2d, 0xb7, 0xd1, 0x3a, 0x76, 0x1f, 0x1a, 0xdf, 0x2c, 0x1d, 0xcf, 0xb7, 0xea,
	0x34, 0x29, 0x05, 0xf6, 0x00, 0x9a, 0xb3, 0xc4, 0x49, 0xd2, 0xd8, 0x6a, 0x0c, 0x2a, 0x43, 0x66,
	0x2b, 0x89, 0x59, 0xb0, 0x6d, 0x87, 0xbe, 0x98, 0x8c, 0x67, 0x56, 0x73, 0x50, 0x1b, 0xb6, 0x6d,
	0x2d, 0xb2, 0x7d, 0x68, 0x91, 0xef, 0xaf, 0x2e, 0x12, 0x6b, 0x7b, 0x50, 0x19, 0xee, 0xec, 0x3f,
	0x18, 0x51, 0x08, 0xd0, 0x1b, 0x3d, 0xe3, 0x85, 0x41, 0x6c, 0x67, 0x76, 0xfc, 0x1c, 0x76, 0xd4,
	0xff, 0xc6, 0xa9, 0x9f, 0xb0, 0x47, 0x50, 0x1f, 0x3b, 0x89, 0x63, 0x55, 0x06, 0xb5, 0xe1, 0xce,
	0x7e, 0x2f, 0x5f, 0x3e, 0x9b, 0x2f, 0xc4, 0xd2, 0xb1, 0x69, 0x96, 0x7d, 0x01, 0x30, 0x75, 0xce,
	0x84, 0x5c, 0x43, 0xbf, 0x9d, 0x1d, 0x35, 0x75, 0xce, 0xbc, 0xc0, 0xc1, 0x53, 0xe4, 0xac, 0x6d,
	0x58, 0xf2, 0x73, 0xe8, 0x95, 0x5d, 0xc1, 0x00, 0x4d, 0x82, 0xb9, 0x9f, 0xba, 0x02, 0x7f, 0x23,
	0xa6, 0x20, 0xb7, 0xec, 0x82, 0x8e, 0x3d, 0x83, 0x36, 0xee, 0x32, 0x75, 0x22, 0x67, 0xa9, 0x8e,
	0x7b, 0xbf, 0x7c, 0x1c, 0x4d, 0xda, 0xb9, 0x1d, 0xff, 0x01, 0xba, 0xcf, 0x45, 0x82, 0xe7, 0x69,
	0x2c, 0x7b, 0x50, 0x3b, 0xf1, 0x5c, 0x05, 0x23, 0x0e, 0x0b, 0x11, 0xab, 0x5e, 0x33, 0x62, 0x9f,
	0xc2, 0xee, 0x58, 0xf8, 0x22, 0x11, 0x1b, 0xb7, 0xe6, 0x2f, 0x60, 0xf7, 0xe4, 0xc2, 0x75, 0xfe,
	0xc5, 0x0c, 0x03, 0x8e, 0x06, 0xea, 0xf4, 0x35, 0x01, 0xc7, 0x31, 0x3f, 0x84, 0x87, 0xf9, 0x66,
	0x32, 0x0f, 0xae, 0xde, 0x32, 0x4f, 0x9c, 0xaa, 0x99, 0x38, 0xfc, 0xf7, 0x0a, 0xec, 0x1e, 0xa6,
	0x51, 0x24, 0x02, 0x15, 0x15, 0x42, 0xbc, 0x0f, 0x2d, 0x5b, 0xcc, 0xc3, 0xc8, 0x9d, 0x8c, 0x75,
	0x82, 0x6b, 0xb9, 0x90, 0xfc, 0xd5, 0x52, 0xf2, 0xd3, 0xba, 0x42, 0x52, 0xb7, 0xcc, 0x84, 0x9e,
	0x2e, 0xc2, 0x40, 0x50, 0xe6, 0xb6, 0x6d, 0x29, 0xe4, 0x69, 0xde, 0x34, 0xd3, 0xfc, 0x43, 0x68,
	0x23, 0xc8, 0xb8, 0x2e, 0xb6, 0xb6, 0x29, 0xa1, 0x73, 0x05, 0xf7, 0x74, 0x14, 0xa7, 0x4e, 0xbc,
	0xe1, 0x97, 0x07, 0xb0, 0xf3, 0xca, 0x77, 0xd1, 0xe6, 0x32, 0x8c, 0x5c, 0xe5, 0xab, 0xa9, 0x42,
	0x8b, 0x23, 0x71, 0x99, 0x59, 0x48, 0x8f, 0x4d, 0x15, 0xef, 0x00, 0x1c, 0xa5, 0xbe, 0xaf, 0x52,
	0xf5, 0x8f, 0x2a, 0x40, 0x0e, 0xc3, 0x9d, 0x44, 0xa9, 0x0f, 0xad, 0xcc, 0x1f, 0xc9, 0xfc, 0x4c,
	0xbe, 0x51, 0x04, 0x73, 0xbc, 0xb7, 0xcb, 0x85, 0xe2, 0x30, 0x12, 0x4e, 0x12, 0x46, 0x56, 0x8b,
	0xec, 0xb5, 0xc8, 0xbe, 0x84, 0x36, 0x0d, 0x85, 0x7b, 0x90, 0x58, 0x6d, 0xca, 0xbc, 0xfe, 0x48,
	0x96, 0xc6, 0x91, 0x2e, 0x8d, 0xa3, 0x63, 0x5d, 0x1a, 0xed, 0xdc, 0x98, 0x3d, 0x82, 0x86, 0xa4,
	0x29, 0x50, 0x81, 0xe8, 0xe6, 0xf9, 0x8a, 0x6a, 0x5b, 0x4e, 0x72, 0x2e, 0x23, 0x82, 0x02, 0x7a,
	0x27, 0xeb, 0x93, 0x8a, 0x9b, 0x92, 0xf8, 0x10, 0x7a, 0xe5, 0x5a, 0x81, 0xff, 0x77, 0x1c, 0x26,
	0x8e, 0x4f, 0xa6, 0xcc, 0x96, 0x02, 0x7f, 0x01, 0xf7, 0x4a, 0x34, 0xc7, 0xa4, 0x41, 0xa2, 0x4f,
	0x02, 0x57, 0xbc, 0x55, 0xc6, 0xb9, 0x42, 0x06, 0xf6, 0x4c, 0xcc, 0xbc, 0x9f, 0x85, 0xa2, 0x40,
	0x26, 0xf3, 0x5f, 0xaa, 0xd2, 0xb7, 0xd9, 0x22, 0xbc, 0xbc, 0xdb, 0xdc, 0xaf, 0xaf, 0x45, 0xae,
	0xb1, 0x1e, 0xb9, 0x66, 0x01, 0xb9, 0x02, 0x3e, 0xdb, 0x37, 0xc1, 0xe7, 0xb1, 0xc6, 0xa7, 0x65,
	0x16, 0x70, 0x54, 0xa9, 0x7a, 0xa2, 0x10, 0x7a, 0x03, 0xef, 0xe9, 0x28, 0x98, 0xe5, 0x9f, 0x17,
	0xca, 0xbf, 0x81, 0x2e, 0x1a, 0xde, 0xb2, 0xf8, 0xff, 0x55, 0x01, 0xc8, 0x1d, 0xd9, 0x18, 0x7b,
	0x06, 0x75, 0x23, 0xee, 0x75, 0x1d, 0xf3, 0x19, 0xf2, 0x3f, 0x98, 0xcb, 0x98, 0x33, 0x3b, 0x93,
	0xd1, 0xfe, 0xa5, 0x58, 0x86, 0x2a, 0xe4, 0x34, 0x36, 0xb3, 0xbf, 0xb1, 0x21, 0xfb, 0x9b, 0x37,
	0xcc, 0xfe, 0x97, 0x22, 0x48, 0x65, 0x9d, 0xca, 0xe2, 0x83, 0x3f, 0x85, 0x6a, 0x5b, 0x4e, 0xf2,
	0x1f, 0xa1, 0xa5, 0x55, 0x88, 0x30, 0x7e, 0xf3, 0xec, 0x97, 0x12, 0x7a, 0x77, 0x30, 0xa7, 0x9b,
	0xc5, 0xaa, 0xca, 0x4b, 0x5c, 0x89, 0x54, 0x0f, 0x45, 0x1c, 0xa6, 0xd1, 0x5c, 0xc4, 0x56, 0x4d,
	0xd5, 0x43, 0xad, 0xe0, 0xbf, 0x55, 0xa0, 0x8b, 0x9b, 0x13, 0x68, 0x19, 0x17, 0x74, 0xe0, 0x62,
	0x02, 0x8e, 0x16, 0x28, 0xc5, 0x55, 0xa1, 0xc4, 0xf7, 0x87, 0x99, 0xbe, 0x5a, 0x46, 0x87, 0x11,
	0xef, 0xc9, 0x58, 0x05, 0x53, 0x49, 0x85, 0x9b, 0xb2, 0x61, 0x62, 0x9e, 0x79, 0xb3, 0xee, 0x6d,
	0xd1, 0x2b, 0xcf, 0x1a, 0xd7, 0xbd, 0x8c, 0x64, 0xf1, 0xba, 0x27, 0xdd, 0x7f, 0xbb, 0xee, 0x43,
	0xb8, 0x97, 0x1d, 0xb6, 0xe9, 0x31, 0x63, 0x70, 0xe1, 0x76, 0xf9, 0xfc, 0xae, 0x06, 0x80, 0xfe,
	0xde, 0x4d, 0x3e, 0x4f, 0xe6, 0x61, 0xa0, 0xf3, 0x19, 0xc7, 0xb2, 0x8e, 0xa6, 0x89, 0xd0, 0xe9,
	0xac, 0x24, 0xd4, 0x7f, 0xeb, 0xb9, 0xae, 0x08, 0x74, 0x0d, 0x91, 0x92, 0x2c, 0x82, 0x78, 0xd7,
	0x4f, 0xc6, 0x54, 0x42, 0xe8, 0x76, 0x91, 0x32, 0xfb, 0x18, 0x7f, 0x19, 0xc7, 0x53, 0x27, 0x59,
	0xa8, 0xcb, 0xc1, 0xd0, 0x98, 0xdc, 0x69, 0x6f, 0xe0, 0x0e, 0xdc, 0x84, 0x3b, 0x4f, 0xf2, 0x8c,
	0xdf, 0x31, 0xf1, 0xc0, 0x10, 0xca, 0x89, 0x9c, 0x03, 0x4f, 0x4d, 0x0e, 0x74, 0xc8, 0x9a, 0xe5,
	0xd6, 0x7a, 0xca, 0xe4, 0xc5, 0x67, 0x12, 0x0b, 0xb9, 0x01, 0xc6, 0xef, 0x30, 0x74, 0xf5, 0x83,
	0x9d, 0xc6, 0xeb, 0x30, 0xe0, 0xa7, 0xd0, 0x31, 0x37, 0xbc, 0xee, 0x3a, 0xc9, 0xea, 0x64, 0x11,
	0xea, 0x77, 0x84, 0x92, 0xd0, 0x96, 0x22, 0xaa, 0x70, 0xc3, 0x31, 0x31, 0x16, 0x0f, 0xb9, 0x36,
	0x63, 0x4d, 0x76, 0x56, 0x4b, 0xec, 0x34, 0x41, 0xad, 0x95, 0x40, 0x7d, 0x02, 0xbd, 0x69, 0x24,
	0x5e, 0x7b, 0x6f, 0x0d, 0x68, 0xa5, 0x23, 0x2b, 0x7a, 0x23, 0x69, 0x1a, 0x66, 0xd2, 0xf0, 0x5f,
	0x2b, 0xd0, 0xcb, 0x9c, 0xd5, 0x94, 0x7d, 0x0c, 0x5d, 0x45, 0x4f, 0x0d, 0xa0, 0x24, 0x6d, 0x49,
	0x8b, 0x0e, 0xe8, 0x57, 0x7b, 0x06, 0x5e, 0x95, 0x2c, 0x57, 0xf4, 0x45, 0x8a, 0xd7, 0xae, 0x4f,
	0xf1, 0xcc, 0xb9, 0x4d, 0x14, 0xcf, 0x59, 0x79, 0x4b, 0x8a, 0xff, 0x59, 0x85, 0x16, 0x6e, 0x76,
	0x1c, 0x09, 0xf1, 0xbf, 0x22, 0xb8, 0x41, 0xc6, 0xf6, 0x8d, 0xc8, 0x08, 0xd7, 0x20, 0x23, 0x7b,
	0x02, 0xad, 0xc3, 0x85, 0xe7, 0xbb, 0x91, 0x08, 0x14, 0xd7, 0xbb, 0xf9, 0x02, 0x8c, 0xa5, 0x9d,
	0xcd, 0xef, 0xbf, 0xab, 0xcb, 0x06, 0x88, 0x3d, 0x85, 0x06, 0x01, 0xcb, 0xd4, 0xe6, 0x66, 0x17,
	0xde, 0xdf, 0x2d, 0xe8, 0x08, 0x9b, 0x2d, 0xf6, 0x15, 0xb4, 0x49, 0x41, 0x4f, 0xb9, 0x75, 0xab,
	0x3e, 0x28, 0xbe, 0x5f, 0x8a, 0xab, 0x47, 0xd0, 0x94, 0xc5, 0x89, 0xad, 0x34, 0x5d, 0xfd, 0x15,
	0x0d, 0xdf, 0x62, 0x9f, 0x43, 0x53, 0xb6, 0x7d, 0xec, 0xa1, 0x9c, 0x5d, 0x69, 0x02, 0xf5, 0x32,
	0xa3, 0x8b, 0xd8, 0x62, 0x7b, 0x50, 0x7b, 0x2e, 0x12, 0x76, 0x5f, 0x4e, 0x15, 0x1b, 0xd2, 0xab,
	0xce, 0x91, 0x1d, 0x8f, 0x3e, 0x67, 0xa5, 0x8b, 0x5c, 0xbb, 0xec, 0x00, 0x3a, 0x64, 0xe8, 0xa8,
	0x27, 0xe4, 0x47, 0xe5, 0xc5, 0x85, 0xae, 0x71, 0xad, 0xab, 0x07, 0xd4, 0x30, 0x1b, 0x1d, 0xe2,
	0x15, 0x5e, 0x2b, 0xbf, 0x56, 0x5a, 0x49, 0xbe, 0xc5, 0xbe, 0x86, 0x6e, 0xde, 0xae, 0x51, 0x23,
	0x53, 0xf8, 0x09, 0xa3, 0x89, 0x5b, 0xe7, 0xc1, 0x69, 0x93, 0xae, 0x90, 0x67, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0x12, 0xc1, 0x4f, 0xb9, 0x11, 0x00, 0x00,
}
